# Assignment

Task 1. Create a 4x4 matrix with values ranging from 0 to 3.\

In [1]:
import numpy as np
x = np.zeros((4, 4))
x[::] = np.arange(4)
print(x)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


Task 2. Create and array with shape of 4x4 and turn it into two arrays along the second axis

In [2]:
b = np.arange(1, 17).reshape(4,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
y = np.hsplit(b, 2)
print(y)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
